name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag l00145375/production:tagname
    - name: Push the Docker Image
      run: docker login -u ijn35807 -p ${{ secrets.PRODUCTION }} && docker push l00145375/production:tagname
